name: dombrowski
start_with_trigger_images: false
ignore_triggerarea: false
use_softlabels: true
ignore_prediction: false
eval_targetlabel: ${targetlabel}
optimize_targetlabel: null
y_groundtruth: false
y_trigger: false
y_original: true